const passport = require("passport");
const GoogleStrategy = require("passport-google-oauth20").Strategy;
const keys = require("../config/keys");
const mongoose = require("mongoose");
const User = mongoose.model("users");
passport.serializeUser((user,done)=>{
    //generating indentifying info for cookie
    //next time fetch out to deserisliaze
    done(null,user.id);
    //user.id!=profile.id,generated by the mongo:_id
});

passport.deserializeUser((id,done)=>{
    User.findById(id).then(user=>{
        done(null,user);
    });
});

passport.use(new GoogleStrategy({
    clientID:keys.googleClientID,
    clientSecret:keys.googleClientSecret,
    callbackURL:"/auth/google/callback",
    proxy:true
},(accessToken,refreshToken,profile,done)=> {
    console.log("accessToken",accessToken);
    console.log("refreshToken",refreshToken);
    User.findOne({googleId:profile.id}).then(existinguser=>{
        if(existinguser) {
            done(null,existinguser);
        } else {
            new User({googleId:profile.id}).save()
            .then(user=>done(null,user));
            
        }
    });
    
    
}));

